//
//  CRTOJSONConstants.h
//  advertiser-sdk
//
//  Copyright (c) 2015 Criteo. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString* const kCRTOJSONAttributionPropertyAcKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONAttributionPropertyChannelKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONAttributionPropertyVKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONAttributionPropertyValueKey;

FOUNDATION_EXPORT NSString* const kCRTOJSONCustomerIdPropertyEmailKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONCustomerIdPropertyMKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONCustomerIdPropertyHKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONCustomerIdPropertyHash_MethodKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONCustomerIdPropertyIKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONCustomerIdPropertyLoginKey;

FOUNDATION_EXPORT NSString* const kCRTOJSONDeviceInfoDevice_ManufacturerKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONDeviceInfoDevice_ModelKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONDeviceInfoPlatformKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONDeviceInfoOs_NameKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONDeviceInfoOs_VersionKey;

FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeAlKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeAppLaunchKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeSetHashedEmailKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeSetHashedLoginKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeCeKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeClKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeSetEmailKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeSetLoginKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeExdKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeSetDataKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeCallDisingKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeDisKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeTrackTransactionKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeVcKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeVbKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeViewBasketKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeVhKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeViewHomeKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeViewListKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeViewListingKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeVlKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeViewItemKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeViewProductKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeVpKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeViewSearchKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeVsKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONEventTypeAppDeeplinkKey;

FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyAnKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyApp_CountryKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyApp_IdKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyApp_LanguageKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyApp_NameKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyApp_VersionKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyCnKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyCountry_CodeKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyLanguage_CodeKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertyLnKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPartnerAppDataPropertySdk_VersionKey;

FOUNDATION_EXPORT NSString* const kCRTOJSONProductPropertyIKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONProductPropertyIdKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONProductPropertyPKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONProductPropertyPrKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONProductPropertyPriceKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONProductPropertyQKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONProductPropertyQuantityKey;

FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameAKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameAccountKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameAiKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameApp_InfoKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameAtKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameAttributionKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameCheckin_DateKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameDinKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameCheckout_DateKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameDevice_InfoKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameDoutKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameCKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameCurrencyKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameDataKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameDebugKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameEbsKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameEKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameEventKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameEventsKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameFirst_LaunchKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameIdfaKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameIdKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameKeywordsKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameKwKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameItemKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNamePKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameProductKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameProductsKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameBKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNamePublisherKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameSite_TypeKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameTimestampKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameTransaction_ValueKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameTvKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameIpKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameVKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameVersionKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyValueDcKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONPropertyNameDeeplink_UriKey;

FOUNDATION_EXPORT NSString* const kCRTOJSONSiteTypeDesktopKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONSiteTypeIn_App_AndroidKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONSiteTypeIn_App_IosKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONSiteTypeMobileKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONSiteTypeTabletKey;

FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperCiKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperCustomer_IdKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperDdKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperDeduplicationKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperDrKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperNcKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperNew_CustomerKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperPt2Key;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperRefKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperSiKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperUser_SegmentKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperSite_TypeKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONUniversalTagParametersHelperVurlKey;

FOUNDATION_EXPORT NSString* const kCRTOJSONExtraDataValueKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONExtraDataTypeKey;
FOUNDATION_EXPORT NSString* const kCRTOJSONExtraDataTypeDateValue;
FOUNDATION_EXPORT NSString* const kCRTOJSONExtraDataTypeFloatValue;
FOUNDATION_EXPORT NSString* const kCRTOJSONExtraDataTypeIntegerValue;
FOUNDATION_EXPORT NSString* const kCRTOJSONExtraDataTypeTextValue;

FOUNDATION_EXPORT NSString* const kCRTOJSONProtocolVersionValue1_0_0;


@interface CRTOJSONConstants : NSObject

+ (BOOL) isKeyReserved:(NSString*)key;

@end
