# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'CriteoDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CriteoEventsSDK', :path => '../'

  # Pods for CriteoDemo

  target 'CriteoDemoTests' do
    inherit! :search_paths
    pod 'Nocilla'
    pod 'OCMock'
    # Pods for testing
  end

end
